source 'http://rubygems.org'
ruby '2.4.0'

gem 'rubygems-update'
gem 'bundler'
gem 'sinatra'
gem 'rest-open-uri'
gem 'json', '~> 2.1.0'
gem 'rmeetup'
gem 'rest-client'
gem 'addressable'
gem 'unicorn'
gem 'puma'

gem 'datamapper'
